# Generated by Django 5.1.6 on 2025-03-18 11:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, verbose_name='Username')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('first_name', models.CharField(max_length=30, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=150, verbose_name='Last Name')),
                ('words_learned', models.PositiveIntegerField(default=0, verbose_name='Words Learned')),
                ('texts_read', models.PositiveIntegerField(default=0, verbose_name='Texts Read')),
                ('tests_completed', models.PositiveIntegerField(default=0, verbose_name='Tests Completed')),
                ('streak', models.PositiveIntegerField(default=0, verbose_name='Current Streak')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
