# Generated by Django 5.1.7 on 2025-03-25 14:45

import django.db.models.deletion
import profilepage.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badge_type', models.CharField(choices=[('words', 'Words'), ('texts', 'Texts'), ('tests', 'Tests')], max_length=10)),
                ('level', models.IntegerField(choices=[(1, 'Bronze'), (2, 'Silver'), (3, 'Gold')])),
                ('achieved_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-achieved_at'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, verbose_name='Username')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('first_name', models.CharField(max_length=30, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=150, verbose_name='Last Name')),
                ('words_learned', models.PositiveIntegerField(default=0, verbose_name='Words Learned')),
                ('texts_read', models.PositiveIntegerField(default=0, verbose_name='Texts Read')),
                ('tests_completed', models.PositiveIntegerField(default=0, verbose_name='Tests Completed')),
                ('streak', models.PositiveIntegerField(default=0, verbose_name='Current Streak')),
                ('friends_count', models.PositiveIntegerField(default=0, verbose_name='Friends Count')),
                ('followers_count', models.PositiveIntegerField(default=0, verbose_name='Followers Count')),
                ('avatar', models.ImageField(default='avatars/default_user.png', upload_to=profilepage.models.avatar_upload_path, verbose_name='Avatar')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
