# Generated by Django 5.1.6 on 2025-03-18 11:26

import profilepage.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profilepage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='avatars/default_user.png', upload_to=profilepage.models.avatar_upload_path, verbose_name='Avatar'),
        ),
    ]
