# Generated by Django 5.1.7 on 2025-03-24 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profilepage', '0002_profile_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='followers_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Followers Count'),
        ),
        migrations.AddField(
            model_name='profile',
            name='friends_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Friends Count'),
        ),
    ]
