# Generated by Django 5.1.7 on 2025-04-05 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profilepage', '0002_profile_bio_profile_birth_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='study_start_date',
            field=models.DateField(auto_now_add=True, verbose_name='Study Start Date'),
        ),
    ]
