# Generated by Django 5.1.7 on 2025-03-25 10:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profilepage', '0003_profile_followers_count_profile_friends_count'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badge_type', models.CharField(choices=[('words', 'Words'), ('texts', 'Texts'), ('tests', 'Tests')], max_length=10)),
                ('level', models.IntegerField(choices=[(1, 'Bronze'), (2, 'Silver'), (3, 'Gold')])),
                ('achieved_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-achieved_at'],
            },
        ),
    ]
