# Generated by Django 5.1.7 on 2025-04-05 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profilepage', '0003_alter_profile_study_start_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='hide_personal_info',
        ),
        migrations.AddField(
            model_name='profile',
            name='hide_birth_date',
            field=models.BooleanField(default=False, verbose_name='Hide Birth Date'),
        ),
        migrations.AddField(
            model_name='profile',
            name='hide_first_name',
            field=models.BooleanField(default=False, verbose_name='Hide First Name'),
        ),
        migrations.AddField(
            model_name='profile',
            name='hide_last_name',
            field=models.BooleanField(default=False, verbose_name='Hide Last Name'),
        ),
    ]
