# Generated by Django 5.1.6 on 2025-05-30 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profilepage', '0004_remove_profile_hide_personal_info_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='english_level',
            field=models.CharField(choices=[('A0', 'A0'), ('A1', 'A1'), ('A2', 'A2'), ('B1', 'B1'), ('B2', 'B2'), ('C1', 'C1'), ('C2', 'C2')], default='A1', max_length=2, verbose_name='English Level'),
        ),
    ]
