# Generated by Django 5.1.6 on 2025-06-06 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profilepage', '0011_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='last_visit_date',
            field=models.DateField(blank=True, null=True, verbose_name='Last Visit Date'),
        ),
    ]
