# Generated by Django 5.1.6 on 2025-06-06 08:40

import django.db.models.deletion
import profilepage.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('profilepage', '0012_profile_last_visit_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='achievement',
            options={'ordering': ['-achieved_at'], 'verbose_name': 'Achievement', 'verbose_name_plural': 'Achievements'},
        ),
        migrations.AlterModelOptions(
            name='friendship',
            options={'ordering': ['-created_at'], 'verbose_name': 'Friendship', 'verbose_name_plural': 'Friendships'},
        ),
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created_at'], 'verbose_name': 'Notification', 'verbose_name_plural': 'Notifications'},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Profile', 'verbose_name_plural': 'Profiles'},
        ),
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='username',
        ),
        migrations.AlterField(
            model_name='achievement',
            name='achieved_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Achieved At'),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='badge_type',
            field=models.CharField(choices=[('words', 'Words'), ('texts', 'Texts'), ('tests', 'Tests')], max_length=10, verbose_name='Badge Type'),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='level',
            field=models.IntegerField(choices=[(1, 'Bronze'), (2, 'Silver'), (3, 'Gold')], verbose_name='Level'),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='friendship',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='friendship',
            name='from_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friendship_requests_sent', to=settings.AUTH_USER_MODEL, verbose_name='From User'),
        ),
        migrations.AlterField(
            model_name='friendship',
            name='status',
            field=models.CharField(choices=[('requested', 'Requested'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='requested', max_length=10, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='friendship',
            name='to_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friendship_requests_received', to=settings.AUTH_USER_MODEL, verbose_name='To User'),
        ),
        migrations.AlterField(
            model_name='friendship',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Content Type'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='is_read',
            field=models.BooleanField(default=False, verbose_name='Is Read'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='message',
            field=models.TextField(verbose_name='Message'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('FRIEND_REQUEST', 'Friend Request'), ('SYSTEM', 'System Notification'), ('ACHIEVEMENT', 'Achievement Unlocked')], max_length=20, verbose_name='Notification Type'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Object ID'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='avatars/default_user.png', upload_to=profilepage.models.avatar_upload_path),
        ),
        migrations.AlterField(
            model_name='profile',
            name='english_level',
            field=models.CharField(choices=[('A0', 'Beginner (A0)'), ('A1', 'Elementary (A1)'), ('A2', 'Pre-Intermediate (A2)'), ('B1', 'Intermediate (B1)'), ('B2', 'Upper-Intermediate (B2)'), ('C1', 'Advanced (C1)'), ('C2', 'Proficiency (C2)')], default='A0', max_length=2, verbose_name='English Level'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterUniqueTogether(
            name='achievement',
            unique_together={('user', 'badge_type', 'level')},
        ),
    ]
