# Generated by Django 5.1.6 on 2025-06-06 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profilepage', '0013_alter_achievement_options_alter_friendship_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='website',
        ),
    ]
