# Generated by Django 5.1.6 on 2025-07-01 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profilepage', '0014_remove_profile_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendship',
            name='was_rejected',
            field=models.BooleanField(default=False),
        ),
    ]
