from django.urls import path
from . import views

urlpatterns = [
    path('', views.grammar_list, name='grammar_page'),


    path('verb/', views.verbs_topic_list, name='verbs_page'),
    path('verb/classification_of_english_verbs/', views.classification_of_english_verbs,
         name='classification_of_english_verbs_page'),
    path('verb/regular_and_irregular_verbs', views.regular_and_irregular_verbs, name='regular_and_irregular_verbs'),
    path('verb/table_of_irregular_verbs', views.table_of_irregular_verbs, name='table_of_irregular_verbs'),
    path('verb/person_and_number_of_the_english_verb', views.person_and_number_of_the_english_verb,
         name='person_and_number_of_the_english_verb'),
    path('verb/transitive_and_intransitive_verbs', views.transitive_and_intransitive_verbs,
         name='transitive_and_intransitive_verbs'),
    path('verb/verb_to_be/', views.verb_to_be, name='verb_to_be'),
    path('verb/verb_to_have/', views.verb_to_have, name='verb_to_have'),
    path('verb/verb_to_do/', views.verb_to_do, name='verb_to_do'),
    path('verb/finite_and_non_finite_forms_of_the_verb/', views.finite_and_non_finite_forms_of_the_verb,
         name='finite_and_non_finite_forms_of_the_verb'),
    path('verb/infinitive/', views.infinitive, name='infinitive'),
    path('verb/gerund/', views.gerund, name='gerund'),
    path('verb/participle/', views.participle, name='participle'),
    path('verb/present_simple/', views.present_simple, name='present_simple'),
    path('verb/present_continuous/', views.present_continuous, name='present_continuous'),
    path('verb/present_perfect/', views.present_perfect, name='present_perfect'),
    path('verb/present_perfect_continuous/', views.present_perfect_continuous, name='present_perfect_continuous'),
    path('verb/past_simple/', views.past_simple, name='past_simple'),
    path('verb/past_continuous/', views.past_continuous, name='past_continuous'),
    path('verb/past_perfect/', views.past_perfect, name='past_perfect'),
    path('verb/past_perfect_continuous/', views.past_perfect_continuous, name='past_perfect_continuous'),
    path('verb/future_simple/', views.future_simple, name='future_simple'),
    path('verb/future_continuous/', views.future_continuous, name='future_continuous'),
    path('verb/future_perfect/', views.future_perfect, name='future_perfect'),
    path('verb/future_perfect_continuous/', views.future_perfect_continuous, name='future_perfect_continuous'),
    path('verb/sequence_of_tenses_general_rule/', views.the_sequence_of_tenses_general_rule,
         name='the_sequence_of_tenses_general_rule'),
    path('verb/sequence_of_tenses_exceptions/', views.the_sequence_of_tenses_exceptions,
         name='the_sequence_of_tenses_exceptions'),
    path('verb/subjunctive_mood/', views.subjunctive_mood, name='subjunctive_mood'),
    path('verb/indicative_mood/', views.indicative_mood, name='indicative_mood'),
    path('verb/immperative_mood/', views.immperative_mood, name='immperative_mood'),
    path('verb/passive_voice/', views.passive_voice, name='passive_voice'),
    path('verb/active_voise/', views.active_voice, name='active_voice'),
    path('verb/modal_verb_can_or_could/', views.modal_verb_can_or_could, name='modal_verb_can_or_could'),
    path('verb/modal_verb_may_or_might/', views.modal_verb_may_or_might, name='modal_verb_may_or_might'),
    path('verb/modal_verb_must_or_have_to/', views.modal_verb_must_or_have_to, name='modal_verb_must_or_have_to'),
    path('verb/modal_verb_have_to_or_have_got_to/', views.modal_verb_have_to_or_have_got_to,
         name='modal_verb_have_to_or_have_got_to'),
    path('verb/modal_verb_be_to/', views.modal_verb_be_to, name='modal_verb_be_to'),
    path('verb/modal_verb_need/', views.modal_verb_need, name='modal_verb_need'),
    path('verb/modal_verb_ought_to/', views.modal_verb_ought_to, name='modal_verb_ought_to'),
    path('verb/modal_verb_should/', views.modal_verb_should, name='modal_verb_should'),
    path('verb/modal_verb_would/', views.modal_verb_would, name='modal_verb_would'),
    path('verb/modal_verb_shall_or_will/', views.modal_verb_shall_or_will, name='modal_verb_shall_or_will'),
    path('verb/modal_verb_dare/', views.modal_verb_dare, name='modal_verb_dare'),
    path('verb/modal_verb_used_to/', views.modal_verb_used_to, name='modal_verb_used_to'),
    path('verb/phrasal_verbs/', views.phrasal_verbs, name='phrasal_verbs'),



    path('noun/', views.noun_topic_list, name='noun_page'),
    path('noun/proper_vs_common_nouns/', views.proper_vs_common_nouns, name='proper_vs_common_nouns'),
    path('noun/concrete_vs_abstract/', views.concrete_vs_abstract, name='concrete_vs_abstract'),
    path('noun/countable_or_uncountable/', views.countable_or_uncountable, name='countable_or_uncountable'),
    path('noun/collective_nouns/', views.collective_nouns, name='collective_nouns'),
    path('noun/compound_nouns/', views.compound_nouns, name='compound_nouns'),
    path('noun/natural_gender/', views.natural_gender, name='natural_gender'),
    path('noun/male_female_pairs/', views.male_female_pairs, name='male_female_pairs'),
    path('noun/gender_suffixes/', views.gender_suffixes, name='gender_suffixes'),
    path('noun/gender_neutral_terms/', views.gender_neutral_terms, name='gender_neutral_terms'),
    path('noun/gender_in_pronouns/', views.gender_in_pronouns, name='gender_in_pronouns'),
    path('noun/regular_plurals_s_or_es/)', views.regular_plurals_s_or_es, name='regular_plurals_s_or_es'),
    path('noun/nouns_ending_in_y_or_o_or_f/', views.nouns_ending_in_y_or_o_or_f, name='nouns_ending_in_y_or_o_or_f'),
    path('noun/irregular_plurals/', views.irregular_plurals, name='irregular_plurals'),
    path('noun/zero_plurals/', views.zero_plurals, name='zero_plurals'),
    path('noun/always_plural_nouns/', views.always_plural_nouns, name='always_plural_nouns'),
    path('noun/latin_and_greek_plurals/', views.latin_and_greek_plurals, name='latin_and_greek_plurals'),
    path('noun/common_case/', views.common_case, name='common_case'),
    path('noun/possessive_case/', views.possessive_case, name='possessive_case'),
    path('noun/subject_or_object_functions/', views.subject_or_object_functions, name='subject_or_object_functions'),
    path('noun/joint_possession/', views.joint_possession, name='joint_possession'),
    path('noun/possessive_determiners/', views.possessive_determiners, name='possessive_determiners'),
    path('noun/demonstratives/', views.demonstratives, name='demonstratives'),
    path('noun/quantifiers/', views.quantifiers, name='quantifiers'),
    path('noun/interrogative_determiners/', views.interrogative_determiners, name='interrogative_determiners'),
    path('noun/subject_of_verb/', views.subject_of_verb, name='subject_of_verb'),
    path('noun/direct_or_indirect_object/', views.direct_or_indirect_object, name='direct_or_indirect_object'),
    path('noun/object_of_preposition/', views.object_of_preposition, name='object_of_preposition'),
    path('noun/subject_complement/', views.subject_complement, name='subject_complement'),
    path('noun/appositive/', views.appositive, name='appositive'),
    path('noun/collective_nouns_for_people/', views.collective_nouns_for_people, name='collective_nouns_for_people'),
    path('noun/collective_nouns_for_animals/', views.collective_nouns_for_animals, name='collective_nouns_for_animals'),
    path('noun/collective_nouns_for_objects/', views.collective_nouns_for_objects, name='collective_nouns_for_objects'),
    path('noun/verb_agreement_rules/', views.verb_agreement_rules, name='verb_agreement_rules'),
    path('noun/bre_vs_ame_usage/', views.bre_vs_ame_usage, name='bre_vs_ame_usage'),
    path('noun/key_uses_of_indefinite_articles/', views.key_uses_of_indefinite_articles,

         name='key_uses_of_indefinite_articles'),




    path('article/', views.articles_topic_list, name='articles_page'),
    path('article/introduction_to_articles', views.introduction_to_articles, name='introduction_to_articles'),
    path('article/types_of_articles/', views.types_of_articles, name='types_of_articles'),
    path('article/summary_table/', views.summary_table, name='summary_table'),
    path('article/core_function_specificity/', views.core_function_specificity, name='core_function_specificity'),
    path('article/usage_with_categories/', views.usage_with_categories, name='usage_with_categories'),
    path('article/usage_with_geographic_names/', views.usage_with_geographic_names, name='usage_with_geographic_names'),
    path('article/other_specific_uses/', views.other_specific_uses, name='other_specific_uses'),
    path('article/using_a_vs_an/', views.using_a_vs_an, name='using_a_vs_an'),
    path('article/situations_without_indefinite_articles/', views.situations_without_indefinite_articles,
         name='situations_without_indefinite_articles'),
    path('article/zero_article_with_general_nouns/', views.zero_article_with_general_nouns,
         name='zero_article_with_general_nouns'),
    path('article/zero_article_with_proper_nouns/', views.zero_article_with_proper_nouns,
         name='zero_article_with_proper_nouns'),
    path('article/zero_article_with_fixed_expressions/', views.zero_article_with_fixed_expressions,
         name='zero_article_with_fixed_expressions'),
    path('article/before_noun/', views.before_noun, name='before_noun'),
    path('article/before_adjective/', views.before_adjective, name='before_adjective'),
    path('article/after_determiners/', views.after_determiners, name='after_determiners'),



    path('adjective/', views.adjective_topic_list, name='adjective_page'),
    path('adjective/morphological_structure/', views.morphological_structure, name='morphological_structure'),
    path('adjective/syntactic_functions/', views.syntactic_functions, name='syntactic_functions'),
    path('adjective/positive_comparative_and_superlative/', views.positive_comparative_and_superlative,
         name='positive_comparative_and_superlative'),
    path('adjective/formation_rules/', views.formation_rules, name='formation_rules'),
    path('adjective/irregular_forms/', views.irregular_forms, name='irregular_forms'),
    path('adjective/absolute_adjectives/', views.absolute_adjectives, name='absolute_adjectives'),
    path('adjective/to_refer_to_a_group_of_people/', views.to_refer_to_a_group_of_people,
         name='to_refer_to_a_group_of_people'),
    path('adjective/to_refer_to_abstract_concepts/', views.to_refer_to_abstract_concepts,
         name='to_refer_to_abstract_concepts'),
    path('adjective/as_singular_and_plural_nouns/', views.as_singular_and_plural_nouns,
         name='as_singular_and_plural_nouns'),
    path('adjective/standard_order_osascomp/', views.standard_order_osascomp, name='standard_order_osascomp'),
    path('adjective/examples_of_usage_the_adjective/', views.examples_of_usage_the_adjective,
         name='examples_of_usage_the_adjective'),
    path('adjective/attributive_function/', views.attributive_function, name='attributive_function'),
    path('adjective/predicative_function/', views.predicative_function, name='predicative_function'),
    path('adjective/object_complement/', views.object_complement, name='object_complement'),
    path('adjective/appositive_and_introductory/', views.appositive_and_introductory,
         name='appositive_and_introductory'),




    path('pronoun/', views.pronoun_topic_list, name='pronoun_page'),
    path('pronoun/definition_and_purpose/', views.definition_and_purpose, name='definition_and_purpose'),
    path('pronoun/grammatical_features/', views.grammatical_features, name='grammatical_features'),
    path('pronoun/personal_and_possessive_pronouns/', views.personal_and_possessive_pronouns,
         name='personal_and_possessive_pronouns'),
    path('pronoun/demonstrative_pronouns/', views.demonstrative_pronouns, name='demonstrative_pronouns'),
    path('pronoun/interrogative_and_relative_pronouns/', views.interrogative_and_relative_pronouns,
         name='interrogative_and_relative_pronouns'),
    path('pronoun/indefinite_pronouns/', views.indefinite_pronouns, name='indefinite_pronouns'),
    path('pronoun/reflexive_intensive_and_reciprocal_pronouns/', views.reflexive_intensive_and_reciprocal_pronouns,
         name='reflexive_intensive_and_reciprocal_pronouns'),
    path('pronoun/pronoun_antecedent_agreement/', views.pronoun_antecedent_agreement,
         name='pronoun_antecedent_agreement'),
    path('pronoun/grammatical_functions_in_a_sentence/', views.grammatical_functions_in_a_sentence,
         name='grammatical_functions_in_a_sentence'),
    path('pronoun/common_usage_pitfalls/', views.common_usage_pitfalls, name='common_usage_pitfalls'),



    path('numeral/', views.numeral_topic_list, name='numeral_page'),
    path('numeral/cardinal_numerals_definition_and_formation/', views.cardinal_numerals_definition_and_formation,
         name='cardinal_numerals_definition_and_formation'),
    path('numeral/spelling_and_hyphenation/', views.spelling_and_hyphenation, name='spelling_and_hyphenation'),
    path('numeral/usage_and_pluralization/', views.usage_and_pluralization, name='usage_and_pluralization'),
    path('numeral/ordinal_numerals_definition_and_formation/', views.ordinal_numerals_definition_and_formation,
         name='ordinal_numerals_definition_and_formation'),
    path('numeral/spelling_rules_and_exceptions/', views.spelling_rules_and_exceptions,
         name='spelling_rules_and_exceptions'),
    path('numeral/usage_with_articles_and_prepositions/', views.usage_with_articles_and_prepositions,
         name='usage_with_articles_and_prepositions'),
    path('numeral/simple_fractions/', views.simple_fractions, name='simple_fractions'),
    path('numeral/decimal_fractions/', views.decimal_fractions, name='decimal_fractions'),
    path('numeral/reading_mixed_numbers/', views.reading_mixed_numbers, name='reading_mixed_numbers'),
    path('numeral/noun_agreement_with_fractions/', views.noun_agreement_with_fractions,
         name='noun_agreement_with_fractions'),
    path('numeral/reading_years_and_dates/', views.reading_years_and_dates, name='reading_years_and_dates')
,   path('numeral/expressing_time/', views.expressing_time, name='expressing_time'),
    path('numeral/other_numerical_data/', views.other_numerical_data, name='other_numerical_data'),
    path('numeral/usage_with_royalty_and_sequence/', views.usage_with_royalty_and_sequence,
         name='usage_with_royalty_and_sequence'),
    path('numeral/cardinal_numerals_as_nouns/', views.cardinal_numerals_as_nouns, name='cardinal_numerals_as_nouns'),
    path('numeral/ordinal_numerals_as_nouns/', views.ordinal_numerals_as_nouns, name='ordinal_numerals_as_nouns'),
    path('numeral/common_phrases_and_usage/', views.common_phrases_and_usage, name='common_phrases_and_usage'),




    path('adverb/', views.adverb_topic_list, name='adverb_page'),
    path('adverb/modifying_verbs_adjectives_and_other_adverbs/', views.modifying_verbs_adjectives_and_other_adverbs,
         name='modifying_verbs_adjectives_and_other_adverbs'),
    path('adverb/modifying_entire_sentences/', views.modifying_entire_sentences, name='modifying_entire_sentences'),
    path('adverb/formation_of_adverbs/', views.formation_of_adverbs, name='formation_of_adverbs'),
    path('adverb/adverbs_of_manner_place_and_time/', views.adverbs_of_manner_place_and_time,
         name='adverbs_of_manner_place_and_time'),
    path('adverb/adverbs_of_frequency_and_degree/', views.adverbs_of_frequency_and_degree,
         name='adverbs_of_frequency_and_degree'),
    path('adverb/interrogative_relative_and_conjunctive_adverbs/', views.interrogative_relative_and_conjunctive_adverbs,
         name='interrogative_relative_and_conjunctive_adverbs'),
    path('adverb/positive_comparative_and_superlative_forms/', views.positive_comparative_and_superlative_forms,
         name='positive_comparative_and_superlative_forms'),
    path('adverb/formation_rules_of_comparison/', views.formation_rules_of_comparison,
         name='formation_rules_of_comparison'),
    path('adverb/irregular_forms_of_comparison/', views.irregular_forms_of_comparison,
         name='irregular_forms_of_comparison'),
    path('adverb/general_positions_of_adverbs/', views.general_positions_of_adverbs,
         name='general_positions_of_adverbs'),
    path('adverb/placement_for_specific_adverb_types/', views.placement_for_specific_adverb_types,
         name='placement_for_specific_adverb_types'),
    path('adverb/order_of_adverbs_mpt_rule/', views.order_of_adverbs_mpt_rule, name='order_of_adverbs_mpt_rule'),



    path('preposition/', views.preposition_topic_list, name='preposition_page'),
    path('preposition/definition_and_functions/', views.preposition_definition_and_functions,
         name='preposition_definition_and_functions'),
    path('preposition/simple_compound_and_phrasal/', views.simple_compound_and_phrasal_prepositions,
         name='simple_compound_and_phrasal_prepositions'),
    path('preposition/prepositional_phrases/', views.understanding_prepositional_phrases,
         name='understanding_prepositional_phrases'),
    path('preposition/grammatical_role/', views.grammatical_role_of_prepositions,
         name='grammatical_role_of_prepositions'),
    path('preposition/semantic_relationships/', views.semantic_relationships, name='semantic_relationships'),
    path('preposition/standard_placement/', views.standard_placement, name='standard_placement'),
    path('preposition/end_placement/', views.end_placement, name='end_placement'),
    path('preposition/common_scenarios_end_placement/', views.common_scenarios_for_end_placement,
         name='common_scenarios_for_end_placement'),
    path('preposition/at_on_in/', views.at_on_in_usage, name='at_on_in_usage'),
    path('preposition/about_above_below/', views.about_above_below_usage, name='about_above_below_usage'),
    path('preposition/after_and_before/', views.after_and_before_usage, name='after_and_before_usage'),
    path('preposition/by_for_and_from/', views.by_for_and_from_usage, name='by_for_and_from_usage'),
    path('preposition/of_since_to_with/', views.of_since_to_with_usage, name='of_since_to_with_usage'),



    path('conjunction/', views.conjunction_topic_list, name='conjunction_page'),
    path('conjunction/definition_and_function/', views.conjunction_definition_and_function,
         name='conjunction_definition_and_function'),
    path('conjunction/types_of_conjunctions/', views.types_of_conjunctions, name='types_of_conjunctions'),
    path('conjunction/coordinating_conjunctions/', views.coordinating_conjunctions, name='coordinating_conjunctions'),
    path('conjunction/subordinating_conjunctions/', views.subordinating_conjunctions,
         name='subordinating_conjunctions'),
    path('conjunction/correlative_conjunctions/', views.correlative_conjunctions, name='correlative_conjunctions'),
    path('conjunction/conjunction_vs_preposition/', views.conjunction_vs_preposition,
         name='conjunction_vs_preposition'),
    path('conjunction/conjunction_vs_adverb/', views.conjunction_vs_adverb, name='conjunction_vs_adverb'),
    path('conjunction/key_differences_and_examples/', views.key_differences_and_examples,
         name='key_differences_and_examples'),



    path('particle/', views.particle_topic_list, name='particle_page'),
    path('particle/what_is_a_particle/', views.what_is_a_particle, name='what_is_a_particle'),
    path('particle/types_of_particles/', views.types_of_particles, name='types_of_particles'),
    path('particle/phrasal_verbs/', views.forming_phrasal_verbs, name='forming_phrasal_verbs'),
    path('particle/infinitives/', views.creating_infinitives, name='creating_infinitives'),
    path('particle/negations/', views.forming_negations, name='forming_negations'),
    path('particle/discourse_markers/', views.as_discourse_markers, name='as_discourse_markers'),
    path('particle/vs_adverbs/', views.particles_vs_adverbs, name='particles_vs_adverbs'),
    path('particle/vs_prepositions/', views.particles_vs_prepositions, name='particles_vs_prepositions'),
    path('particle/key_differences/', views.key_differences_and_functions, name='key_differences_and_functions'),



    path('interjection/', views.interjection_topic_list, name='interjection_page'),
    path('interjection/what_is_an_interjection/', views.what_is_an_interjection, name='what_is_an_interjection'),
    path('interjection/usage_and_punctuation/', views.usage_and_punctuation, name='usage_and_punctuation'),
    path('interjection/common_interjections/', views.common_interjections_by_emotion,
         name='common_interjections_by_emotion'),


    path('main_sentence_part/', views.main_sentence_part_topic_list, name='main_sentence_part_page'),
    path('main_sentence_part/subject_definition_and_function/', views.subject_definition_and_function,
         name='subject_definition_and_function'),
    path('main_sentence_part/what_can_be_a_subject/', views.what_can_be_a_subject,
         name='what_can_be_a_subject'),
    path('main_sentence_part/position_and_types_of_subjects/', views.position_and_types_of_subjects,
         name='position_and_types_of_subjects'),
    path('main_sentence_part/predicate_definition_and_function/', views.predicate_definition_and_function,
         name='predicate_definition_and_function'),
    path('main_sentence_part/components_of_the_predicate/', views.components_of_the_predicate,
         name='components_of_the_predicate'),
    path('main_sentence_part/types_of_predicates/', views.types_of_predicates, name='types_of_predicates'),

    path('minor_sentence_part/', views.minor_sentence_part_topic_list, name='minor_sentence_part_page'),
    path('minor-sentence-part/object_definition_and_purpose/', views.object_definition_and_purpose,
         name='object_definition_and_purpose'),
    path('minor-sentence-part/direct_and_indirect_objects/', views.direct_and_indirect_objects,
         name='direct_and_indirect_objects'),
    path('minor-sentence-part/object_of_a_preposition/', views.object_of_a_preposition, name='object_of_a_preposition'),
    path('minor-sentence-part/attribute_definition_and_function/', views.attribute_definition_and_function,
         name='attribute_definition_and_function'),
    path('minor-sentence-part/what_can_be_an_attribute/', views.what_can_be_an_attribute, name='what_can_be_an_attribute'),
    path('minor-sentence-part/position_of_the_attribute/', views.position_of_the_attribute, name='position_of_the_attribute'),
    path('minor-sentence-part/adverbial_modifier_definition_and_purpose/',
         views.adverbial_modifier_definition_and_purpose, name='adverbial_modifier_definition_and_purpose'),
    path('minor-sentence-part/what_can_be_an_adverbial_modifier/', views.what_can_be_an_adverbial_modifier,
         name='what_can_be_an_adverbial_modifier'),
    path('minor-sentence-part/types_of_adverbial_modifiers/', views.types_of_adverbial_modifiers,
         name='types_of_adverbial_modifiers'),



    path('simple_sentences/', views.simple_sentences_topic_list, name='simple_sentences_page'),
    path('simple_sentences/key_characteristics/', views.simple_sentences_key_characteristics,
         name='simple_sentences_key_characteristics'),
    path('simple_sentences/examples/', views.simple_sentences_examples, name='simple_sentences_examples'),
    path('simple_sentences/by_purpose/', views.simple_sentences_by_purpose, name='simple_sentences_by_purpose'),
    path('simple_sentences/by_structure/', views.simple_sentences_by_structure, name='simple_sentences_by_structure'),



    path('complex_sentences/', views.complex_sentences_topic_list, name='complex_sentences_page'),
    path('complex_sentences/compound_definition_and_structure/', views.compound_definition_and_structure, name='compound_definition_and_structure'),
    path('complex_sentences/coordinating_conjunctions/', views.complex_sentences_coordinating_conjunctions, name='complex_sentences_coordinating_conjunctions_coordinating_conjunctions'),
    path('complex_sentences/semicolons/', views.semicolons, name='semicolons'),
    path('complex_sentences/complex_definition_and_components/', views.complex_definition_and_components, name='complex_definition_and_components'),
    path('complex_sentences/subordinating_conjunctions/', views.complex_sentences_subordinating_conjunctions, name='complex_sentences_subordinating_conjunctions'),
    path('complex_sentences/subordinating_conjunctions/', views.relative_pronouns, name='relative_pronouns'),
    path('complex_sentences/zero_and_first_conditional/', views.zero_and_first_conditional, name='zero_and_first_conditional'),
    path('complex_sentences/second_and_third_conditional/', views.second_and_third_conditional, name='second_and_third_conditional'),
    path('complex_sentences/mixed_conditionals/', views.mixed_conditionals, name='mixed_conditionals'),



    path('indirect_speech/', views.indirect_speech_topic_list, name='indirect_speech_page'),
    path('indirect_speech/verb_tense_changes/', views.indirect_speech_verb_tense_changes,
         name='indirect_speech_verb_tense_changes'),
    path('indirect_speech/pronoun_changes/', views.indirect_speech_pronoun_changes,
         name='indirect_speech_pronoun_changes'),
    path('indirect_speech/time_and_place_changes/', views.indirect_speech_time_and_place_changes,
         name='indirect_speech_time_and_place_changes'),
    path('indirect_speech/reporting_verbs_and_structure/', views.indirect_speech_reporting_verbs_and_structure,
         name='indirect_speech_reporting_verbs_and_structure'),
    path('indirect_speech/rules_for_backshift/', views.indirect_speech_rules_for_backshift,
         name='indirect_speech_rules_for_backshift'),
    path('indirect_speech/examples_of_tense_sequence/', views.indirect_speech_examples_of_tense_sequence,
         name='indirect_speech_examples_of_tense_sequence'),
    path('indirect_speech/exceptions_to_backshift/', views.indirect_speech_exceptions_to_backshift,
         name='indirect_speech_exceptions_to_backshift'),

    path('punctuation/', views.punctuation_topic_list, name='punctuation_page'),
 path('punctuation/full_stop_declarative/', views.punctuation_full_stop_declarative, name='punctuation_full_stop_declarative'),
    path('punctuation/full_stop_abbreviations/', views.punctuation_full_stop_abbreviations, name='punctuation_full_stop_abbreviations'),
    path('punctuation/comma_list/', views.punctuation_comma_list, name='punctuation_comma_list'),
    path('punctuation/comma_clauses/', views.punctuation_comma_clauses, name='punctuation_comma_clauses'),
    path('punctuation/comma_introductory/', views.punctuation_comma_introductory, name='punctuation_comma_introductory'),
    path('punctuation/comma_non_essential/', views.punctuation_comma_non_essential, name='punctuation_comma_non_essential'),
    path('punctuation/question_mark_interrogative/', views.punctuation_question_mark_interrogative, name='punctuation_question_mark_interrogative'),
    path('punctuation/question_mark_tag_questions/', views.punctuation_question_mark_tag_questions, name='punctuation_question_mark_tag_questions'),
    path('punctuation/exclamation_mark_emotion/', views.punctuation_exclamation_mark_emotion, name='punctuation_exclamation_mark_emotion'),
    path('punctuation/exclamation_mark_commands/', views.punctuation_exclamation_mark_commands, name='punctuation_exclamation_mark_commands'),
    path('punctuation/semicolon_clauses/', views.punctuation_semicolon_clauses, name='punctuation_semicolon_clauses'),
    path('punctuation/semicolon_complex_lists/', views.punctuation_semicolon_complex_lists, name='punctuation_semicolon_complex_lists'),
    path('punctuation/colon_list_explanation/', views.punctuation_colon_list_explanation, name='punctuation_colon_list_explanation'),
    path('punctuation/colon_separating_clauses/', views.punctuation_colon_separating_clauses, name='punctuation_colon_separating_clauses'),
    path('punctuation/apostrophe_possession/', views.punctuation_apostrophe_possession, name='punctuation_apostrophe_possession'),
    path('punctuation/apostrophe_contractions/', views.punctuation_apostrophe_contractions, name='punctuation_apostrophe_contractions'),
    path('punctuation/quotation_marks_direct_speech/', views.punctuation_quotation_marks_direct_speech, name='punctuation_quotation_marks_direct_speech'),
    path('punctuation/quotation_marks_titles/', views.punctuation_quotation_marks_titles, name='punctuation_quotation_marks_titles'),
    path('punctuation/parentheses_brackets_extra_info/', views.punctuation_parentheses_extra_info, name='punctuation_parentheses_extra_info'),
    path('punctuation/parentheses_brackets_clarification/', views.punctuation_brackets_clarification, name='punctuation_brackets_clarification'),
    path('punctuation/hyphen_dash_compound_words/', views.punctuation_hyphen_compound_words, name='punctuation_hyphen_compound_words'),
    path('punctuation/hyphen_dash_emphasis/', views.punctuation_dash_emphasis, name='punctuation_dash_emphasis'),
]