# Generated by Django 5.1.6 on 2025-06-07 11:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EnglishLevelTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Test Title')),
                ('description', models.TextField(blank=True, verbose_name='Test Description')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active Test')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'English Level Test',
                'verbose_name_plural': 'English Level Tests',
                'permissions': [('can_view_english_level_test', 'Can view English level test')],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Question Text')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='testspage.englishleveltest', verbose_name='Test')),
            ],
            options={
                'verbose_name': 'Question',
                'verbose_name_plural': 'Questions',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255, verbose_name='Answer Text')),
                ('is_correct', models.BooleanField(default=False, verbose_name='Is Correct')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='testspage.question', verbose_name='Question')),
            ],
            options={
                'verbose_name': 'Answer',
                'verbose_name_plural': 'Answers',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='UserTestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveIntegerField(verbose_name='Score')),
                ('total_questions', models.PositiveIntegerField(verbose_name='Total Questions')),
                ('percentage', models.FloatField(verbose_name='Correct Percentage')),
                ('english_level_determined', models.CharField(blank=True, choices=[('A0', 'Beginner (A0)'), ('A1', 'Elementary (A1)'), ('A2', 'Pre-Intermediate (A2)'), ('B1', 'Intermediate (B1)'), ('B2', 'Upper-Intermediate (B2)'), ('C1', 'Advanced (C1)'), ('C2', 'Proficiency (C2)')], max_length=2, null=True, verbose_name='Determined English Level')),
                ('completed_at', models.DateTimeField(auto_now_add=True, verbose_name='Completion Date')),
                ('last_level_test_completion', models.DateTimeField(blank=True, null=True, verbose_name='Last Level Test Completion')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='testspage.englishleveltest', verbose_name='Test')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_results', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'User Test Result',
                'verbose_name_plural': 'User Test Results',
                'ordering': ['-completed_at'],
            },
        ),
    ]
