# Generated by Django 5.1.6 on 2025-06-07 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testspage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertestresult',
            name='max_possible_score',
            field=models.PositiveIntegerField(default=0, verbose_name='Maximum Possible Score'),
        ),
    ]
