# Generated by Django 5.1.7 on 2025-04-11 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cardspage', '0004_alter_card_user_card_id_quizsession_quizquestion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizsession',
            name='user',
        ),
        migrations.DeleteModel(
            name='QuizQuestion',
        ),
        migrations.DeleteModel(
            name='QuizSession',
        ),
    ]
