# Generated by Django 5.1.7 on 2025-05-20 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0002_customuser_first_name_customuser_last_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
    ]
