# Generated by Django 5.1.6 on 2025-06-02 19:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textspage', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='text',
            name='read_by',
            field=models.ManyToManyField(blank=True, related_name='read_texts', to=settings.AUTH_USER_MODEL, verbose_name='Read By'),
        ),
    ]
